scorer:
- _impl_: RewardModelScorer
  score_id: reward
  model_id: OpenAssistant/reward-model-deberta-v3-large
  batch_size: 8
  trun_len: 1024
  top_k: 1
  device: 0
- _impl_: PerplexityScorer
  score_id: perplexity
  model_id: gpt2
  batch_size: 8
  trun_len: 1024
  device: 0
- _impl_: ToxicityScorer
  score_id: toxicity
  model_id: unitary/toxic-bert
  batch_size: 8
  trun_len: 1024
  device: 0
- _impl_: GibberishScorer
  score_id: gibberish
  model_id: madhurjindal/autonlp-Gibberish-Detector-492513457
  batch_size: 8
  trun_len: 1024
  device: 0
- _impl_: ContradictionScorer
  score_id: contradiction
  model_id: MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli
  batch_size: 8
  trun_len: 1024
  device: 0
- _impl_: LengthScorer
  score_id: length

scorefilter:
  absolute:
  - score_id: reward
    threshold: 0.5
    direction: ge
  - score_id: toxicity
    threshold: 0.1
    direction: le
  - score_id: gibberish
    threshold: 0.1
    direction: le
  - score_id: contradiction
    threshold: 0.5
    direction: le
  - score_id: length
    threshold: 2000
    direction: le
  - score_id: length
    threshold: 10
    direction: ge
  relative:
  - score_id: perplexity
    threshold: 1.65
    direction: le
  - score_id: perplexity
    threshold: -1.65
    direction: ge

clustering:
- _impl_: Dedup
- _impl_: SemanticKmeansClustering
  batch_size: 8
  device: 0
  model_id: facebook/contriever
  n_cluster: 100
  niter: 10
  sample_rate: 0.1
